name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Versão específica

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libffi-dev zlib1g-dev liblzma-dev
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.38
        
    - name: Initialize Buildozer
      run: |
        buildozer init
        
    - name: Build APK
      run: |
        buildozer android debug
      timeout-minutes: 60  # Mais tempo para build
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always()  # Upload mesmo se falhar
      with:
        name: app-chamadas-apk
        path: bin/*.apk
