name: Simple Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install basic dependencies
      run: |
        pip install --upgrade pip
        pip install kivy==2.1.0
        
    - name: Create simple test
      run: |
        echo "Workflow básico funcionando!"
